window.addthis_translations = [
    [
        [
            "pt",
            "por"
        ],
        "Adicionar aos favoritos / Compartilhar",
        "Mais...",
        "Enviar e-mail para amigo",
        "E-mail",
        "Favoritos",
        "Vários endereços? Use vírgulas.",
        "Para",
        "De",
        "Nota",
        "Política de privacidade: Nós nunca compartilhamos as suas informações pessoais.",
        "Enviar",
        "Digite um endereço de email válido.",
        "Mensagem enviada!",
        "Assine o nosso Feed",
        "Selecione os leitores de feed web:",
        "Por favor não me pergunte de novo; envie-me diretamente para meu leitor de feed preferido.",
        "Feito",
        "Crie o seu próprio botão!",
        "endereco de e-mail",
        "opcional",
        "Máximo de 255 caracteres",
        "Imprimir",
        "O que é isso?",
        "Privacidade",
        "Usar catálogo de endereços",
        "Cancelar",
        "Faça o login para usar seus contatos",
        "Usuário",
        "Senha",
        "Lembrar-me",
        "Fazer login",
        "Selecione um catálogo de endereços",
        "Erro fazendo login.",
        "Por favor, limite-se a 5 destinatários.",
        "Encontre um serviço",
        "Serviço não encontrado.",
        "Compartilhe novamente.",
        "Fazer logout",
        "Obtendo contatos...",
        "Sugerir um servi&ccedil;o",
        "Compartilhado com sucesso!",
        "Faça a partilha mais fácil com AddThis para Firefox.",
        "Baixar",
        "Esconder isso!",
        "Enviando mensagem ...",
        "Por favor <a id=\"at16ecmc\" href=\"#\" onclick=\"_atw.rse();_atw.cef();return true\" target=\"_blank\">clique aqui</a> para confirmar que você é uma pessoa real-live.",
        "Configurações",
        "Desculpa, mas não poderia enviar este e-mail. Por favor, tente novamente em alguns minutos.",
        "Ajude-nos a evitar e-mails indesejados!",
        "Digite as duas palavras:",
        "Por favor introduza uma resposta válida.",
        "Desculpe, sua resposta era incorreta.",
        "Entrar para personalizar",
        "Assunto",
        "Enviar este e-mail usando serviços diferentes",
        "Digitar as letras em movimento",
        "Entrar para tornar o compartilhamento mais fácil",
        "Assistir a um vídeo",
        "Sucesso registado!",
        "Fechando a janela em segundos XXX ...",
        "Personalizar",
        "Conta",
        "Enviar E-mail",
        "Comentários",
        "Compartilhar uma idéia, relatar um bug, ou deixe-nos saber o que você pensa.",
        "Precisa de ajuda?",
        "Enviar Comentários",
        "Todos Os Serviços Disponíveis",
        "Meus Serviços Favoritos",
        "Redefinir os serviços de padrão",
        "Juntar",
        "Remover",
        "Salvar As Alterações",
        "Personalize AddThis, selecionando-se a 10 de seus lugares favoritos para compartilhar.",
        ,
        ,
        "Facilitar a partilha com a Barra de Ferramentas AddThis",
        "Para parar de receber os e-mails de AddThis visite",
        "Enviado",
        "Seu feedback é muito importante para nós.",
        "Obrigado por utilizar o AddThis",
        "Olá",
        "Ligue contas sociais para ativar Instant Share para o Twitter e Facebook.",
        "Ver vídeo",
        "Todas as contas podem ser usadas para entrar e acessar o resto.",
        "Conecte a outra conta.",
        "Seria triste vê-lo ir, mas você pode excluir sua conta a qualquer momento.",
        "Exclua conta.",
        "Desligar",
        "Reordene esta lista usando as setas. ",
        "Partilhar",
        "Por favor, introduza uma nota menor.",
        "Nós não fomos capazes de enviar seu e-mail.",
        "OK",
        "Ups",
        "Seguir",
        "Obrigado por compartilhar",
        "Obrigado por seguir",
        "Recomendado para você",
        "Compartilhe a [x]",
        "Siga em [x]",
        "Introduza o seu endereço de email",
        "Seu e-mail",
        "Ao clicar no botão acima, estará a dar o seu acordo para que as informações acima sejam enviadas para os servidores da AddThis nos EUA."
    ]
];

window.addthis_services_loc = 'facebook,twitter,print,email,gmail,google_plusone_share,linkedin,pinterest_share,blogger,favorites';
window.addthis_services_loc_mob = 'facebook,whatsapp,twitter,mailto,google_plusone_share,pinterest_share,linkedin,gmail,google_plusone_share,blogger';

if (window._ate) _ate.ed.fire("addthis.i18n.ready", window.addthis, {lng:"pt"});
